// Korean Alphabet (Hangul) Data Structure
// Contains all 14 consonants and 10 vowels with learning information

export const koreanConsonants = [
  {
    id: 1,
    name: 'Kiyeok',
    koreanLetter: 'ㄱ',
    romanization: 'g/k',
    englishSound: 'g/k',
    englishComparison: 'Like "g" in "go" or "k" in "kite" depending on position',
    pictogram: 'square-angle',
    exampleWords: ['go', 'kite', 'key'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a backwards "L" with a small line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '가다 (gada - to go)',
      '고양이 (goyang-i - cat)',
      '기다리다 (gidarida - to wait)',
      '국물 (gukmul - soup)',
      '김치 (kimchi - kimchi)',
      '학교 (hakgyo - school)',
      '한국 (hanguk - Korea)',
      '커피 (keopi - coffee)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 2,
    name: 'Nieun',
    koreanLetter: 'ㄴ',
    romanization: 'n',
    englishSound: 'n',
    englishComparison: 'Like "n" in "now"',
    pictogram: 'line-horizontal',
    exampleWords: ['now', 'noon', 'name'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a horizontal line',
    strokeOrder: [1],
    commonWords: [
      '나 (na - I/me)',
      '나무 (namu - tree)',
      '너 (neo - you)',
      '노래 (norae - song)',
      '눈 (nun - eye or snow)',
      '날다 (nalda - to fly)',
      '남자 (namja - man)',
      '내일 (naeil - tomorrow)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 3,
    name: 'Digeut',
    koreanLetter: 'ㄷ',
    romanization: 'd/t',
    englishSound: 'd/t',
    englishComparison: 'Like "d" in "dog" or "t" in "top" depending on position',
    pictogram: 'square-angle',
    exampleWords: ['dog', 'top', 'day'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a square bracket facing right',
    strokeOrder: [1, 2],
    commonWords: [
      '다 (da - all)',
      '도시 (dosi - city)',
      '대하다 (daehada - to treat)',
      '독서 (dokseo - reading)',
      '닭 (dak - chicken)',
      '달 (dal - moon)',
      '동물 (dongmul - animal)',
      '땅 (ttang - ground)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 4,
    name: 'Rieul',
    koreanLetter: 'ㄹ',
    romanization: 'r/l',
    englishSound: 'r/l',
    englishComparison: 'Like "r" in "run" or "l" in "lamp" depending on position',
    pictogram: 'line-diagonal',
    exampleWords: ['run', 'lamp', 'red'],
    category: 'consonant',
    difficulty: 2,
    visualAid: 'Like two diagonal lines meeting',
    strokeOrder: [1, 2],
    commonWords: [
      '라 (ra - as/like)',
      '로 (ro - with/by)',
      '리 (ri - lee)',
      '루 (ru - roux)',
      '레 (re - re)',
      '러 (reo - Russia)',
      '래 (rae - ray)',
      '려 (ryeo - yeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 5,
    name: 'Mieum',
    koreanLetter: 'ㅁ',
    romanization: 'm',
    englishSound: 'm',
    englishComparison: 'Like "m" in "mouse"',
    pictogram: 'square',
    exampleWords: ['mouse', 'man', 'more'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a square',
    strokeOrder: [1, 2, 3, 4],
    commonWords: [
      '마 (ma - ma)',
      '모 (mo - mo)',
      '미 (mi - mi)',
      '무 (mu - mu)',
      '메 (me - me)',
      '머 (meo - meo)',
      '매 (mae - mae)',
      '먀 (mya - mya)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 6,
    name: 'Bieup',
    koreanLetter: 'ㅂ',
    romanization: 'b/p',
    englishSound: 'b/p',
    englishComparison: 'Like "b" in "boy" or "p" in "park" depending on position',
    pictogram: 'square-angle',
    exampleWords: ['boy', 'park', 'big'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a square with a lid',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '바 (ba - ba)',
      '보 (bo - bo)',
      '비 (bi - bi)',
      '부 (bu - bu)',
      '베 (be - be)',
      '버 (beo - beo)',
      '배 (bae - bae)',
      '벼 (byeo - byeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 7,
    name: 'Si-ot',
    koreanLetter: 'ㅅ',
    romanization: 's/t',
    englishSound: 's/t',
    englishComparison: 'Like "s" in "sing" or "t" in "top" depending on position',
    pictogram: 'line-horizontal',
    exampleWords: ['sing', 'top', 'sit'],
    category: 'consonant',
    difficulty: 2,
    visualAid: 'Like two horizontal lines',
    strokeOrder: [1, 2],
    commonWords: [
      '사 (sa - sa)',
      '소 (so - so)',
      '시 (si - si)',
      '수 (su - su)',
      '세 (se - se)',
      '서 (seo - seo)',
      '새 (sae - sae)',
      '셔 (syeo - syeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 8,
    name: 'Ieung',
    koreanLetter: 'ㅇ',
    romanization: 'ng/-',
    englishSound: 'ng/silent',
    englishComparison: 'Like "ng" in "sing" or silent at syllable start',
    pictogram: 'circle',
    exampleWords: ['sing', 'ring', 'song'],
    category: 'consonant',
    difficulty: 1,
    visualAid: 'Like a circle',
    strokeOrder: [1],
    commonWords: [
      '아 (a - ah)',
      '오 (o - oh)',
      '이 (i - ee)',
      '우 (u - oo)',
      '에 (e - eh)',
      '어 (eo - uh)',
      '애 (ae - ae)',
      '여 (yeo - yuh)'
    ],
    syllablePosition: 'initial/final'
  },
  {
    id: 9,
    name: 'Jieut',
    koreanLetter: 'ㅈ',
    romanization: 'j/t',
    englishSound: 'j/t',
    englishComparison: 'Like "j" in "jump" or "t" in "church" depending on position',
    pictogram: 'square-angle',
    exampleWords: ['jump', 'church', 'jet'],
    category: 'consonant',
    difficulty: 2,
    visualAid: 'Like a backwards "C" with a line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '자 (ja - ja)',
      '조 (jo - jo)',
      '지 (ji - ji)',
      '주 (ju - ju)',
      '제 (je - je)',
      '저 (jeo - jeo)',
      '재 (jae - jae)',
      '져 (jyeo - jyeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 10,
    name: 'Chieut',
    koreanLetter: 'ㅊ',
    romanization: 'ch/t',
    englishSound: 'ch/t',
    englishComparison: 'Like "ch" in "church" or "t" in "top" depending on position',
    pictogram: 'line-horizontal',
    exampleWords: ['church', 'top', 'chip'],
    category: 'consonant',
    difficulty: 3,
    visualAid: 'Like three horizontal lines',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '차 (cha - cha)',
      '초 (cho - cho)',
      '치 (chi - chi)',
      '추 (chu - chu)',
      '체 (che - che)',
      '처 (cheo - cheo)',
      '채 (chae - chae)',
      '쳐 (chyeo - chyeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 11,
    name: 'Kieuk',
    koreanLetter: 'ㅋ',
    romanization: 'k',
    englishSound: 'k',
    englishComparison: 'Like "k" in "kite" (aspirated)',
    pictogram: 'square-angle',
    exampleWords: ['kite', 'key', 'car'],
    category: 'consonant',
    difficulty: 3,
    visualAid: 'Like ㄱ but with extra breath',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '카 (ka - ka)',
      '코 (ko - ko)',
      '키 (ki - ki)',
      '쿠 (ku - ku)',
      '케 (ke - ke)',
      '커 (keo - keo)',
      '캐 (kae - kae)',
      '켜 (kyeo - kyeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 12,
    name: 'Tieut',
    koreanLetter: 'ㅌ',
    romanization: 't',
    englishSound: 't',
    englishComparison: 'Like "t" in "top" (aspirated)',
    pictogram: 'square-angle',
    exampleWords: ['top', 'time', 'take'],
    category: 'consonant',
    difficulty: 3,
    visualAid: 'Like ㄷ but with extra breath',
    strokeOrder: [1, 2],
    commonWords: [
      '타 (ta - ta)',
      '토 (to - to)',
      '티 (ti - ti)',
      '투 (tu - tu)',
      '테 (te - te)',
      '터 (teo - teo)',
      '태 (tae - tae)',
      '터 (tyeo - tyeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 13,
    name: 'Pieup',
    koreanLetter: 'ㅍ',
    romanization: 'p',
    englishSound: 'p',
    englishComparison: 'Like "p" in "park" (aspirated)',
    pictogram: 'square-angle',
    exampleWords: ['park', 'pie', 'put'],
    category: 'consonant',
    difficulty: 3,
    visualAid: 'Like ㅂ but with extra breath',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '파 (pa - pa)',
      '포 (po - po)',
      '피 (pi - pi)',
      '푸 (pu - pu)',
      '페 (pe - pe)',
      '퍼 (peo - peo)',
      '패 (pae - pae)',
      '펴 (pyeo - pyeo)'
    ],
    syllablePosition: 'initial'
  },
  {
    id: 14,
    name: 'Hieut',
    koreanLetter: 'ㅎ',
    romanization: 'h',
    englishSound: 'h',
    englishComparison: 'Like "h" in "house"',
    pictogram: 'line-diagonal',
    exampleWords: ['house', 'hat', 'hope'],
    category: 'consonant',
    difficulty: 2,
    visualAid: 'Like two diagonal lines',
    strokeOrder: [1, 2],
    commonWords: [
      '하 (ha - ha)',
      '호 (ho - ho)',
      '히 (hi - hi)',
      '후 (hu - hu)',
      '헤 (he - he)',
      '허 (heo - heo)',
      '해 (hae - hae)',
      '혀 (hyeo - hyeo)'
    ],
    syllablePosition: 'initial'
  }
];

export const koreanVowels = [
  {
    id: 15,
    name: 'A',
    koreanLetter: 'ㅏ',
    romanization: 'a',
    englishSound: 'ah',
    englishComparison: 'Like "a" in "father"',
    pictogram: 'line-vertical',
    exampleWords: ['father', 'car', 'far'],
    category: 'vowel',
    difficulty: 1,
    visualAid: 'Like a vertical line with a small horizontal branch',
    strokeOrder: [1, 2],
    commonWords: [
      '가 (ga - family)',
      '나 (na - I/me)',
      '다 (da - all)',
      '라 (ra - as/like)',
      '마 (ma - ma)',
      '바 (ba - ba)',
      '사 (sa - sa)',
      '자 (ja - ja)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 16,
    name: 'Ya',
    koreanLetter: 'ㅑ',
    romanization: 'ya',
    englishSound: 'yah',
    englishComparison: 'Like "ya" in "yacht"',
    pictogram: 'line-vertical',
    exampleWords: ['yacht', 'yard', 'yam'],
    category: 'vowel',
    difficulty: 2,
    visualAid: 'Like ㅏ but with an extra line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '야 (ya - ya)',
      '냐 (nya - nya)',
      '댜 (dya - dya)',
      '랴 (rya - rya)',
      '먀 (mya - mya)',
      '뱌 (bya - bya)',
      '샤 (sya - sya)',
      '쟈 (jya - jya)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 17,
    name: 'Eo',
    koreanLetter: 'ㅓ',
    romanization: 'eo',
    englishSound: 'uh',
    englishComparison: 'Like "u" in "but"',
    pictogram: 'line-horizontal',
    exampleWords: ['but', 'cut', 'run'],
    category: 'vowel',
    difficulty: 1,
    visualAid: 'Like a horizontal line with a small vertical branch',
    strokeOrder: [1, 2],
    commonWords: [
      '거 (geo - geo)',
      '너 (neo - neo)',
      '더 (deo - deo)',
      '러 (reo - reo)',
      '머 (meo - meo)',
      '버 (beo - beo)',
      '서 (seo - seo)',
      '저 (jeo - jeo)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 18,
    name: 'Yeo',
    koreanLetter: 'ㅕ',
    romanization: 'yeo',
    englishSound: 'yuh',
    englishComparison: 'Like "yu" in "yule"',
    pictogram: 'line-horizontal',
    exampleWords: ['yule', 'cute', 'pure'],
    category: 'vowel',
    difficulty: 2,
    visualAid: 'Like ㅓ but with an extra line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '겨 (gyeo - gyeo)',
      '녀 (nyeo - nyeo)',
      '뎌 (dyeo - dyeo)',
      '려 (ryeo - ryeo)',
      '며 (myeo - myeo)',
      '벼 (byeo - byeo)',
      '셔 (syeo - syeo)',
      '져 (jyeo - jyeo)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 19,
    name: 'O',
    koreanLetter: 'ㅗ',
    romanization: 'o',
    englishSound: 'oh',
    englishComparison: 'Like "o" in "more"',
    pictogram: 'circle-half',
    exampleWords: ['more', 'door', 'four'],
    category: 'vowel',
    difficulty: 1,
    visualAid: 'Like a horizontal line with a circle above',
    strokeOrder: [1, 2],
    commonWords: [
      '고 (go - go)',
      '노 (no - no)',
      '도 (do - do)',
      '로 (ro - ro)',
      '모 (mo - mo)',
      '보 (bo - bo)',
      '소 (so - so)',
      '조 (jo - jo)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 20,
    name: 'Yo',
    koreanLetter: 'ㅛ',
    romanization: 'yo',
    englishSound: 'yoh',
    englishComparison: 'Like "yo" in "yodel"',
    pictogram: 'circle-half',
    exampleWords: ['yodel', 'yoke', 'yolk'],
    category: 'vowel',
    difficulty: 3,
    visualAid: 'Like ㅗ but with an extra line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '교 (gyo - gyo)',
      '뇨 (nyo - nyo)',
      '됴 (dyo - dyo)',
      '료 (ryo - ryo)',
      '묘 (myo - myo)',
      '뵤 (byo - byo)',
      '쇼 (syo - syo)',
      '죠 (jyo - jyo)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 21,
    name: 'U',
    koreanLetter: 'ㅜ',
    romanization: 'u',
    englishSound: 'oo',
    englishComparison: 'Like "u" in "rude"',
    pictogram: 'circle-half',
    exampleWords: ['rude', 'moon', 'food'],
    category: 'vowel',
    difficulty: 1,
    visualAid: 'Like a horizontal line with a circle below',
    strokeOrder: [1, 2],
    commonWords: [
      '구 (gu - gu)',
      '누 (nu - nu)',
      '두 (du - du)',
      '루 (ru - ru)',
      '무 (mu - mu)',
      '부 (bu - bu)',
      '수 (su - su)',
      '주 (ju - ju)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 22,
    name: 'Yu',
    koreanLetter: 'ㅠ',
    romanization: 'yu',
    englishSound: 'yoo',
    englishComparison: 'Like "yu" in "yule"',
    pictogram: 'circle-half',
    exampleWords: ['yule', 'cute', 'music'],
    category: 'vowel',
    difficulty: 3,
    visualAid: 'Like ㅜ but with an extra line',
    strokeOrder: [1, 2, 3],
    commonWords: [
      '규 (gyu - gyu)',
      '뉴 (nyu - nyu)',
      '듀 (dyu - dyu)',
      '류 (ryu - ryu)',
      '뮤 (myu - myu)',
      '뷰 (byu - byu)',
      '슈 (syu - syu)',
      '쥬 (jyu - jyu)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 23,
    name: 'Eu',
    koreanLetter: 'ㅡ',
    romanization: 'eu',
    englishSound: 'eu',
    englishComparison: 'Like "eu" in "leur" (French)',
    pictogram: 'line-horizontal',
    exampleWords: ['leur', 'sir', 'her'],
    category: 'vowel',
    difficulty: 2,
    visualAid: 'Like a single horizontal line',
    strokeOrder: [1],
    commonWords: [
      '그 (geu - geu)',
      '느 (neu - neu)',
      '드 (deu - deu)',
      '르 (reu - reu)',
      '므 (meu - meu)',
      '브 (beu - beu)',
      '스 (seu - seu)',
      '즈 (jeu - jeu)'
    ],
    syllablePosition: 'medial'
  },
  {
    id: 24,
    name: 'I',
    koreanLetter: 'ㅣ',
    romanization: 'i',
    englishSound: 'ee',
    englishComparison: 'Like "i" in "machine"',
    pictogram: 'line-vertical',
    exampleWords: ['machine', 'see', 'tree'],
    category: 'vowel',
    difficulty: 1,
    visualAid: 'Like a vertical line',
    strokeOrder: [1],
    commonWords: [
      '기 (gi - gi)',
      '니 (ni - ni)',
      '디 (di - di)',
      '리 (ri - ri)',
      '미 (mi - mi)',
      '비 (bi - bi)',
      '시 (si - si)',
      '지 (ji - ji)'
    ],
    syllablePosition: 'medial'
  }
];

// Combined alphabet for easy access
export const koreanAlphabet = [...koreanConsonants, ...koreanVowels];

// Helper function to get random letters
export const getRandomLetters = (count) => {
  const shuffled = [...koreanAlphabet].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Helper function to create syllables
export const createSyllable = (consonant, vowel) => {
  if (!consonant || !vowel) return '';
  return consonant.koreanLetter + vowel.koreanLetter;
};